import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $Outliner } from "@package/net/createmod/catnip/outliner";
import { $LerpedFloat } from "@package/net/createmod/catnip/animation";
import { $SceneBuilder, $SceneBuildingUtil } from "@package/net/createmod/ponder/api/scene";
import { $Entity } from "@package/net/minecraft/world/entity";
import { $PonderLocalization } from "@package/net/createmod/ponder/foundation/registration";
import { $List, $Set, $Collection_ } from "@package/java/util";
import { $PonderUI } from "@package/net/createmod/ponder/foundation/ui";
import { $SuperRenderTypeBuffer } from "@package/net/createmod/catnip/render";
import { $Consumer_, $Function_, $Supplier } from "@package/java/util/function";
import { $BlockPos } from "@package/net/minecraft/core";
import { $StoryBoardEntry$SceneOrderingEntry, $StoryBoardEntry$SceneOrderingEntry_ } from "@package/net/createmod/ponder/api/registration";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $WorldSectionElement, $PonderElement, $ElementLink } from "@package/net/createmod/ponder/api/element";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $ScreenElement } from "@package/net/createmod/catnip/gui/element";
import { $Object, $Class } from "@package/java/lang";
import { $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $BoundingBox } from "@package/net/minecraft/world/level/levelgen/structure";
import { $PonderLevel } from "@package/net/createmod/ponder/api/level";
import { $Vec3_, $Vec3, $Vec2 } from "@package/net/minecraft/world/phys";
import { $Pair } from "@package/net/createmod/catnip/data";
export * as element from "@package/net/createmod/ponder/foundation/element";
export * as instruction from "@package/net/createmod/ponder/foundation/instruction";
export * as registration from "@package/net/createmod/ponder/foundation/registration";
export * as ui from "@package/net/createmod/ponder/foundation/ui";

declare module "@package/net/createmod/ponder/foundation" {
    export class $PonderScene$SceneTransform {
        apply(arg0: $PoseStack, arg1: number): $PoseStack;
        apply(arg0: $PoseStack): $PoseStack;
        tick(): void;
        sceneToScreen(arg0: $Vec3_, arg1: number): $Vec2;
        screenToScene(arg0: number, arg1: number, arg2: number, arg3: number): $Vec3;
        updateScreenParams(arg0: number, arg1: number, arg2: number): void;
        updateSceneRVE(arg0: number): void;
        xRotation: $LerpedFloat;
        yRotation: $LerpedFloat;
        constructor(arg0: $PonderScene);
    }
    export class $PonderTag implements $ScreenElement {
        getDescription(): string;
        getId(): $ResourceLocation;
        getTitle(): string;
        render(arg0: $GuiGraphics, arg1: number, arg2: number): void;
        getMainItem(): $ItemStack;
        constructor(arg0: $ResourceLocation_, arg1: $ResourceLocation_ | null, arg2: $ItemStack_, arg3: $ItemStack_);
        get description(): string;
        get id(): $ResourceLocation;
        get title(): string;
        get mainItem(): $ItemStack;
    }
    export class $PonderScene {
        runWith<E extends $PonderElement>(arg0: $ElementLink<E>, arg1: $Consumer_<E>): void;
        reset(): void;
        begin(): void;
        builder(): $SceneBuilder;
        getBounds(): $BoundingBox;
        getLocation(): $ResourceLocation;
        resolve<E extends $PonderElement>(arg0: $ElementLink<E>): E;
        forEach<T extends $PonderElement>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        forEach(arg0: $Consumer_<$PonderElement>): void;
        getId(): $ResourceLocation;
        getString(arg0: string): string;
        tick(): void;
        getElements(): $Set<$PonderElement>;
        getTitle(): string;
        fadeOut(): void;
        addElement(arg0: $PonderElement): void;
        getTotalTime(): number;
        getNamespace(): string;
        getWorld(): $PonderLevel;
        getTags(): $List<$PonderTag>;
        renderOverlay(arg0: $PonderUI, arg1: $GuiGraphics, arg2: number): void;
        getYOffset(): number;
        getBasePlateOffsetX(): number;
        getBaseWorldSection(): $WorldSectionElement;
        getSceneBuildingUtil(): $SceneBuildingUtil;
        shouldHidePlatformShadow(): boolean;
        getBasePlateOffsetZ(): number;
        applyTo<E extends $PonderElement, F>(arg0: $ElementLink<E>, arg1: $Function_<E, F>): F;
        getTransform(): $PonderScene$SceneTransform;
        setPointOfInterest(arg0: $Vec3_): void;
        rayTraceScene(arg0: $Vec3_, arg1: $Vec3_): $Pair<$ItemStack, $BlockPos>;
        getSceneProgress(): number;
        renderScene(arg0: $SuperRenderTypeBuffer, arg1: $GuiGraphics, arg2: number): void;
        setNextUpEnabled(arg0: boolean): void;
        registerText(arg0: string, ...arg1: $Object[]): $Supplier<string>;
        registerText(arg0: string): $Supplier<string>;
        getScaleFactor(): number;
        resolveOptional<E extends $PonderElement>(arg0: $ElementLink<E>): (E) | undefined;
        setFinished(arg0: boolean): void;
        getOrderingEntries(): $List<$StoryBoardEntry$SceneOrderingEntry>;
        stopCounting(): void;
        getPointOfInterest(): $Vec3;
        forEachVisible<T extends $PonderElement>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        forEachWorldEntity<T extends $Entity>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        getKeyframeTime(arg0: number): number;
        getBasePlateSize(): number;
        addToSceneTime(arg0: number): void;
        getOutliner(): $Outliner;
        getCurrentTime(): number;
        markKeyframe(arg0: number): void;
        linkElement<E extends $PonderElement>(arg0: E, arg1: $ElementLink<E>): void;
        getKeyframeCount(): number;
        isNextUpEnabled(): boolean;
        isFinished(): boolean;
        deselect(): void;
        seekToTime(arg0: number): void;
        static TITLE_KEY: string;
        constructor(arg0: $PonderLevel | null, arg1: $PonderLocalization, arg2: string, arg3: $ResourceLocation_, arg4: $Collection_<$ResourceLocation_>, arg5: $Collection_<$StoryBoardEntry$SceneOrderingEntry_>);
        get bounds(): $BoundingBox;
        get location(): $ResourceLocation;
        get id(): $ResourceLocation;
        get elements(): $Set<$PonderElement>;
        get title(): string;
        get totalTime(): number;
        get namespace(): string;
        get world(): $PonderLevel;
        get tags(): $List<$PonderTag>;
        get YOffset(): number;
        get basePlateOffsetX(): number;
        get baseWorldSection(): $WorldSectionElement;
        get sceneBuildingUtil(): $SceneBuildingUtil;
        get basePlateOffsetZ(): number;
        get transform(): $PonderScene$SceneTransform;
        get sceneProgress(): number;
        get scaleFactor(): number;
        get orderingEntries(): $List<$StoryBoardEntry$SceneOrderingEntry>;
        get basePlateSize(): number;
        get outliner(): $Outliner;
        get currentTime(): number;
        get keyframeCount(): number;
    }
}
