import { $PonderScene, $PonderTag } from "@package/net/createmod/ponder/foundation";
import { $NavigatableSimiScreen } from "@package/net/createmod/catnip/gui";
import { $ItemStack, $ItemStack_ } from "@package/net/minecraft/world/item";
import { $NarratableEntry } from "@package/net/minecraft/client/gui/narration";
import { $Component } from "@package/net/minecraft/network/chat";
import { $LerpedFloat } from "@package/net/createmod/catnip/animation";
import { $Renderable } from "@package/net/minecraft/client/gui/components";
import { $List } from "@package/java/util";
import { $Screen$DeferredTooltipRendering } from "@package/net/minecraft/client/gui/screens";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $Pointing_ } from "@package/net/createmod/catnip/math";
import { $Font, $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $Color } from "@package/net/createmod/catnip/theme";
import { $Couple } from "@package/net/createmod/catnip/data";

declare module "@package/net/createmod/ponder/foundation/ui" {
    export class $PonderUI extends $AbstractPonderScreen {
        static of(arg0: $ResourceLocation_): $PonderUI;
        static of(arg0: $ItemStack_, arg1: $PonderTag): $PonderUI;
        static of(arg0: $ItemStack_): $PonderUI;
        getSubject(): $ItemStack;
        updateIdentifiedItem(arg0: $PonderScene): void;
        getHoveredTooltipItem(): $ItemStack;
        setComfyReadingEnabled(arg0: boolean): void;
        isComfyReadingEnabled(): boolean;
        static renderSpeechBox(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number, arg4: number, arg5: boolean, arg6: $Pointing_, arg7: boolean): void;
        getActiveScene(): $PonderScene;
        coolDownAfterSkip(): void;
        getFontRenderer(): $Font;
        static getPartialTicks(): number;
        seekToTime(arg0: number): void;
        static MENU_BACKGROUND: $ResourceLocation;
        static IDENTIFY: string;
        static NEXT_UP: string;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        static ponderTicks: number;
        static SLOW_TEXT: string;
        static PONDERING_TAG: string;
        static WELCOME: string;
        static CLOSE: string;
        title: $Component;
        static COLOR_HIGHLIGHT: $Couple<$Color>;
        static PREVIOUS: string;
        static MISSING_VANILLA_ENTRY: $Couple<$Color>;
        renderables: $List<$Renderable>;
        static INDEX_TITLE: string;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        static DESCRIPTION: string;
        static COLOR_IDLE: $Couple<$Color>;
        static NEXT: string;
        static IDENTIFY_MODE: string;
        static BACKGROUND_IMPORTANT: $Color;
        static ASSOCIATED: string;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        static PONDERING: string;
        static IN_CHAPTER: string;
        static MISSING_MODDED_ENTRY: $Couple<$Color>;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static COLOR_HOVER: $Couple<$Color>;
        static CATEGORIES: string;
        static FOOTER_SEPARATOR: $ResourceLocation;
        transition: $LerpedFloat;
        static BACKGROUND_TRANSPARENT: $Color;
        static BACKGROUND_FLAT: $Color;
        static REPLAY: string;
        narratables: $List<$NarratableEntry>;
        width: number;
        static ponderPartialTicksPaused: number;
        static COLOR_NAV_ARROW: $Couple<$Color>;
        static THINK_BACK: string;
        static EXIT: string;
        font: $Font;
        get subject(): $ItemStack;
        get hoveredTooltipItem(): $ItemStack;
        get activeScene(): $PonderScene;
        get fontRenderer(): $Font;
        static get partialTicks(): number;
    }
    export class $AbstractPonderScreen extends $NavigatableSimiScreen {
        static MENU_BACKGROUND: $ResourceLocation;
        static IDENTIFY: string;
        static NEXT_UP: string;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        static SLOW_TEXT: string;
        static PONDERING_TAG: string;
        static WELCOME: string;
        static CLOSE: string;
        title: $Component;
        static PREVIOUS: string;
        renderables: $List<$Renderable>;
        static INDEX_TITLE: string;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        static DESCRIPTION: string;
        static NEXT: string;
        static IDENTIFY_MODE: string;
        static ASSOCIATED: string;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        static PONDERING: string;
        static IN_CHAPTER: string;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        static CATEGORIES: string;
        static FOOTER_SEPARATOR: $ResourceLocation;
        transition: $LerpedFloat;
        static REPLAY: string;
        narratables: $List<$NarratableEntry>;
        width: number;
        static COLOR_NAV_ARROW: $Couple<$Color>;
        static THINK_BACK: string;
        static EXIT: string;
        font: $Font;
        constructor();
    }
}
